platform :ios, '8.0'

target 'GiveMeGreen' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Virta

  #pod "MDCSwipeToChoose"

  #pod 'ZLSwipeableView'
  pod 'ZLSwipeableViewSwift'

  #pod 'Firebase/Core'
  #pod 'Firebase/Auth'
  #pod 'Firebase/Storage'
  #pod 'Firebase/Database'
  #pod 'Firebase/Messaging'
  #pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
  #pod "SlackTextViewController"

  target 'GiveMeGreenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
